Repository ArkanisCorporation/ArkanisOverlay, pull requests merged in 2025-05, with the labels that each got.

#207 fix: unbrick the auto updater by removing the expired release token
  src/Arkanis.Overlay.Common/ApplicationConstants.cs
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Server/Services/GitHubReleasesService.cs
Labels: build/publish, deploy-env, critical

#208 Release: RC
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE/default.md
  .releaserc
  ArkanisOverlay.sln
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SUPPORT.md
  docs/images/Windows_UAC-DialogOnly1.png
  docs/images/Windows_UAC-DialogOnly2.png
  src/Arkanis.Overlay.Common/ApplicationConstants.cs
  src/Arkanis.Overlay.Components/Helpers/OverlaySearchContext.cs
  src/Arkanis.Overlay.Components/Shared/GameEntitySearchControls.razor
  src/Arkanis.Overlay.Components/Views/Components/SearchBox.razor
  src/Arkanis.Overlay.Components/Views/SearchView.razor
  src/Arkanis.Overlay.Host.Desktop/Constants.cs
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Desktop/Services/WindowsAutoStartManager.cs
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/OverlaySearchPage.razor
  src/Arkanis.Overlay.Host.Server/Components/App.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/Error.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/Index.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/SearchPage.razor
  src/Arkanis.Overlay.Host.Server/Services/GitHubReleasesService.cs
  src/Arkanis.Overlay.Host.Server/wwwroot/apple-touch-icon.png
  src/Arkanis.Overlay.Host.Server/wwwroot/favicon-96x96.png
  src/Arkanis.Overlay.Host.Server/wwwroot/favicon.ico
  src/Arkanis.Overlay.Host.Server/wwwroot/favicon.png
  src/Arkanis.Overlay.Host.Server/wwwroot/favicon.svg
  src/Arkanis.Overlay.Host.Server/wwwroot/site.webmanifest
  src/Arkanis.Overlay.Host.Server/wwwroot/web-app-manifest-192x192.png
  src/Arkanis.Overlay.Host.Server/wwwroot/web-app-manifest-512x512.png
Labels: release

#209 fix: allow reloading the overlay on exception
  src/Arkanis.Overlay.Components/Shared/Layouts/MainLayout.razor
Labels: ui/ux

#216 fix: server-hosted overlay only usable by the last person to open it
  src/Arkanis.Overlay.Components/Views/Components/SearchBox.razor
  src/Arkanis.Overlay.Components/Views/SearchView.razor
Labels: ui/ux, deploy-env, critical

#219 Release: RC
  src/Arkanis.Overlay.Components/Views/Components/SearchBox.razor
  src/Arkanis.Overlay.Components/Views/SearchView.razor
Labels: release

#221 build: include OpenAPI spec for UEX API directly
  src/Arkanis.Overlay.External.UEX/nswag.json
  src/Arkanis.Overlay.External.UEX/openapi.yaml
Labels: ci, build/publish

#222 ci: add automated release version backpropagation
  .github/workflows/_release.yaml
  .github/workflows/build.yaml
Labels: ci, build/publish

#224 fix: pre-release channel updates
  src/Arkanis.Overlay.Common/Abstractions/IAppVersionProvider.cs
  src/Arkanis.Overlay.Common/ApplicationConstants.cs
  src/Arkanis.Overlay.Common/Enums/HostingMode.cs
  src/Arkanis.Overlay.Common/Models/UpdateChannel.cs
  src/Arkanis.Overlay.Common/Services/AssemblyAppVersionProvider.cs
  src/Arkanis.Overlay.Components/Services/DependencyInjection.cs
  src/Arkanis.Overlay.Components/Shared/AnalyticEventSender.razor
  src/Arkanis.Overlay.Components/Shared/Dialogs/AboutDialog.razor
  src/Arkanis.Overlay.Components/Shared/Dialogs/UserPreferencesEditDialog.razor
  src/Arkanis.Overlay.Components/Shared/UpdateChannelDetails.razor
  src/Arkanis.Overlay.Components/wwwroot/assets/img/MadeByTheCommunity_White.png
  src/Arkanis.Overlay.Domain/Abstractions/Services/IStorageManager.cs
  src/Arkanis.Overlay.Host.Desktop/Helpers/FakeSchedulerFactory.cs
  src/Arkanis.Overlay.Host.Desktop/Helpers/UpdateHelper.cs
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Desktop/Services/ArkanisOverlayUpdateManager.cs
  src/Arkanis.Overlay.Host.Desktop/Services/VelopackAppVersionProvider.cs
  src/Arkanis.Overlay.Host.Desktop/UI/App.xaml.cs
  src/Arkanis.Overlay.Host.Desktop/UI/Windows/OverlayWindow.xaml.cs
  src/Arkanis.Overlay.Host.Desktop/Workers/UpdateProcess.cs
  src/Arkanis.Overlay.Host.Server/Program.cs
  src/Arkanis.Overlay.Infrastructure/Data/ClientOverlayDbContextFactory.cs
  src/Arkanis.Overlay.Infrastructure/Data/Extensions/HostExtensions.cs
  src/Arkanis.Overlay.Infrastructure/DependencyInjection.cs
  src/Arkanis.Overlay.Infrastructure/Services/DependencyInjection.cs
  src/Arkanis.Overlay.Infrastructure/Services/FakeAnalyticsReporter.cs
  src/Arkanis.Overlay.Infrastructure/Services/InMemoryUserPreferencesManager.cs
  src/Arkanis.Overlay.Infrastructure/Services/StorageManager.cs
  src/Arkanis.Overlay.Infrastructure/Services/UserPreferencesJsonFileManager.cs
Labels: refactor, setup/update, critical

#225 refactor: UEX API client (auth) configuration
  src/Arkanis.Overlay.External.UEX/Client.Partials.cs
  src/Arkanis.Overlay.External.UEX/DependencyInjection.cs
  src/Arkanis.Overlay.External.UEX/UexApiClientBase.cs
  src/Arkanis.Overlay.External.UEX/UexApiOptions.cs
  src/Arkanis.Overlay.Host.Desktop/appsettings.json
  src/Arkanis.Overlay.Infrastructure/Options/ConfigurationOptions.cs
Labels: refactor, critical

#231 build: update version of dependencies
  Directory.Packages.props
  global.json
  src/Arkanis.Overlay.Common/Arkanis.Overlay.Common.csproj
  src/Arkanis.Overlay.Common/packages.lock.json
  src/Arkanis.Overlay.Components/Arkanis.Overlay.Components.csproj
  src/Arkanis.Overlay.Components/packages.lock.json
  src/Arkanis.Overlay.Domain/packages.lock.json
  src/Arkanis.Overlay.External.UEX/Arkanis.Overlay.External.UEX.csproj
  src/Arkanis.Overlay.External.UEX/packages.lock.json
  src/Arkanis.Overlay.Host.Desktop/Arkanis.Overlay.Host.Desktop.csproj
  src/Arkanis.Overlay.Host.Desktop/packages.lock.json
  src/Arkanis.Overlay.Host.Server/Arkanis.Overlay.Host.Server.csproj
  src/Arkanis.Overlay.Host.Server/packages.lock.json
  src/Arkanis.Overlay.Infrastructure/Arkanis.Overlay.Infrastructure.csproj
  src/Arkanis.Overlay.Infrastructure/packages.lock.json
  tests/Arkanis.Overlay.Common.UnitTests/Arkanis.Overlay.Common.UnitTests.csproj
  tests/Arkanis.Overlay.Common.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Host.Desktop.UnitTests/Arkanis.Overlay.Host.Desktop.UnitTests.csproj
  tests/Arkanis.Overlay.Host.Server.UnitTests/Arkanis.Overlay.Host.Server.UnitTests.csproj
  tests/Arkanis.Overlay.Host.Server.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Infrastructure.UnitTests/Arkanis.Overlay.Infrastructure.UnitTests.csproj
  tests/Arkanis.Overlay.Infrastructure.UnitTests/packages.lock.json
Labels: build/publish, refactor

#239 fix: update check timer displayed wrong time
  src/Arkanis.Overlay.Components/Shared/Dialogs/AboutDialog.razor
  src/Arkanis.Overlay.Host.Desktop/Services/VelopackAppVersionProvider.cs
Labels: ui/ux

#204 feat: add search result context details display
  src/Arkanis.Overlay.Components/Exceptions/JsInteropException.cs
  src/Arkanis.Overlay.Components/Helpers/EventInterop.cs
  src/Arkanis.Overlay.Components/Helpers/JsComponentInterop.cs
  src/Arkanis.Overlay.Components/Shared/FocusRegion.razor
  src/Arkanis.Overlay.Components/Shared/FocusRegion.razor.js
  src/Arkanis.Overlay.Components/Shared/GameEntityNameLabel.razor
  src/Arkanis.Overlay.Components/Shared/GamePriceLabel.razor
  src/Arkanis.Overlay.Components/Shared/Layouts/MainLayout.razor
  src/Arkanis.Overlay.Components/Shared/PriceTagInfo.razor
  src/Arkanis.Overlay.Components/Shared/QuickAccessContainer.razor
  src/Arkanis.Overlay.Components/Shared/QuickAccessContainer.razor.js
  src/Arkanis.Overlay.Components/Views/Components/PriceTagTable.razor
  src/Arkanis.Overlay.Components/Views/Components/SearchResultItem.razor
  src/Arkanis.Overlay.Components/Views/Components/SearchResultStack.razor
  src/Arkanis.Overlay.Components/Views/SearchView.razor
  src/Arkanis.Overlay.Components/_Imports.razor
  src/Arkanis.Overlay.Domain/Abstractions/Services/IPurchasePriceProvider.cs
  src/Arkanis.Overlay.Domain/Abstractions/Services/IRentPriceProvider.cs
  src/Arkanis.Overlay.Domain/Abstractions/Services/ISalePriceProvider.cs
  src/Arkanis.Overlay.Domain/Models/Game/GameCurrency.cs
  src/Arkanis.Overlay.Domain/Models/Trade/PriceTag.cs
  src/Arkanis.Overlay.Host.Server/Components/Pages/Index.razor
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/FakePriceProvider.cs
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/PriceProviderAggregate.cs
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/PriceProviderBase.cs
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/PurchasePriceProvider.cs
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/RentPriceProvider.cs
  src/Arkanis.Overlay.Infrastructure/Services/PriceProviders/SalePriceProvider.cs
Labels: ui/ux

#244 fix: program cleanup on exit
  src/Arkanis.Overlay.Components/Shared/Dialogs/UserPreferencesEditDialog.razor
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Desktop/Services/WindowsNotifications.cs
  src/Arkanis.Overlay.Host.Desktop/Workers/UpdateProcess.cs
  src/Arkanis.Overlay.Host.Desktop/Workers/WindowTracker.cs
Labels: refactor

#265 ci: fix docker image name for server
  scripts/release-32-publish-server.sh
Labels: ci

#270 Release: Stable
  .github/workflows/_release.yaml
Labels: release

#271 Release: Stable
  .github/workflows/_release.yaml
Labels: ci, release

#273 Release: Stable
  .github/workflows/_release.yaml
Labels: ci, release
