Repository ArkanisCorporation/ArkanisOverlay, pull requests merged in 2025-07, with the labels that each got.

#314 fix: Windows auto-start registration detection
  src/Arkanis.Overlay.Host.Desktop/Services/WindowsAutoStartManager.cs
  src/Arkanis.Overlay.Host.Desktop/Services/WindowsAutoStartStateProvider.cs
Labels: ui/ux, deploy-env

#315 fix: add item category as item property and make it searchable, improve default property sorting
  src/Arkanis.Overlay.Domain/Models/Game/GameEntityName.cs
  src/Arkanis.Overlay.Domain/Models/Game/GameItem.cs
Labels: ui/ux

#324 fix: Trade Run filtering and UI
  src/Arkanis.Overlay.Components/Shared/GameEntitySelectBox.razor
  src/Arkanis.Overlay.Components/Views/InventoryView.razor
  src/Arkanis.Overlay.Components/Views/SearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageLoadCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStagePurchaseCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageSellCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageUnloadCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeDestinationSearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeRouteSearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeRunsInProgressView.razor
  src/Arkanis.Overlay.Domain/Abstractions/IIdentifiable.cs
  src/Arkanis.Overlay.Domain/Models/Game/GameTerminal.cs
  src/Arkanis.Overlay.Infrastructure/Data/Mappers/UexApiDtoMapper.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Local/GameEntitySearchAggregateRepository.cs
Labels: ui/ux

#325 fix: change user preferences defaults
  src/Arkanis.Overlay.Domain/Options/UserPreferences.cs
Labels: ui/ux, deploy-env

#332 fix: add trade module index demo
  src/Arkanis.Overlay.Components/Shared/Dialogs/TradeDestinationSearchDialog.razor
  src/Arkanis.Overlay.Components/Shared/TradeRouteItem.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunPanelContent.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageAcquisitionStepper.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageLoadCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStagePurchaseCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageSaleStepper.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageSellCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageStepper.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageTravelToStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/Components/TradeRunStageUnloadCargoStep.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeDestinationSearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeRouteSearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeRunsInProgressView.razor
  src/Arkanis.Overlay.Domain/Models/Trade/TradeRun.cs
  src/Arkanis.Overlay.Host.Server/Components/Pages/Index.razor
Labels: ui/ux

#337 fix: log output
  .run/Arkanis.Overlay.Host.Desktop.run.xml
  .run/Arkanis.Overlay.Host.Server.run.xml
  Directory.Packages.props
  src/Arkanis.Overlay.Host.Desktop/Arkanis.Overlay.Host.Desktop.csproj
  src/Arkanis.Overlay.Host.Desktop/NativeMethods.txt
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Desktop/appsettings.Development.json
  src/Arkanis.Overlay.Host.Desktop/packages.lock.json
  src/Arkanis.Overlay.Host.Server/Arkanis.Overlay.Host.Server.csproj
  src/Arkanis.Overlay.Host.Server/DependencyInjection.cs
  src/Arkanis.Overlay.Host.Server/appsettings.json
  src/Arkanis.Overlay.Host.Server/packages.lock.json
  tests/Arkanis.Overlay.Host.Desktop.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Host.Server.UnitTests/packages.lock.json
Labels: ui/ux, native

#339 fix: cache invalidation handling issues
  src/Arkanis.Overlay.Components/Helpers/ChangeTokenRegistration.cs
  src/Arkanis.Overlay.Components/Services/OverlayModules.cs
  src/Arkanis.Overlay.Components/Shared/OverlayModuleNavigation.razor
  src/Arkanis.Overlay.Components/Views/InventoryView.razor
  src/Arkanis.Overlay.Components/Views/TradeView.razor
  src/Arkanis.Overlay.Infrastructure/Services/ChangeTokenManager.cs
Labels: ui/ux, critical

#340 Trade route polish
  src/Arkanis.Overlay.Components/Shared/CacheManagement.razor
  src/Arkanis.Overlay.Components/Shared/Dialogs/InventoryEntryCreateDialog.razor
  src/Arkanis.Overlay.Components/Shared/Dialogs/InventoryEntryUpdateDialog.razor
  src/Arkanis.Overlay.Components/Shared/Dialogs/SelectGameLocationDialog.razor
  src/Arkanis.Overlay.Components/Shared/GameEntitySelectBox.razor
  src/Arkanis.Overlay.Components/Shared/TradeRouteItem.razor
  src/Arkanis.Overlay.Components/Views/Components/TradeRouteParty.razor
  src/Arkanis.Overlay.Components/Views/InventoryView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeDestinationSearchView.razor
  src/Arkanis.Overlay.Components/Views/Trade/TradeRouteSearchView.razor
  src/Arkanis.Overlay.Domain/Models/Game/GameCommodity.cs
  src/Arkanis.Overlay.Domain/Models/Game/GameTradeRoute.cs
  src/Arkanis.Overlay.Infrastructure/Data/Mappers/UexApiDtoMapper.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexTradeRouteSyncRepository.cs
Labels: ui/ux

#347 fix: indicate whether terminal of commodity price is within searched location
  src/Arkanis.Overlay.Components/Shared/GameEntityNameCodePart.razor
  src/Arkanis.Overlay.Components/Shared/GameLocationLabel.razor
  src/Arkanis.Overlay.Components/Shared/GameLocationNamePart.razor
  src/Arkanis.Overlay.Components/Shared/Tooltip.razor
  src/Arkanis.Overlay.Components/Views/Components/PriceTagTable.razor
  src/Arkanis.Overlay.Domain/Abstractions/Game/IGameLocation.cs
Labels: ui/ux

#349 fix: disable server pre-rendering (prevents rendering page twice on refresh)
  src/Arkanis.Overlay.Host.Server/Components/App.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/InventoryPage.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/SearchPage.razor
  src/Arkanis.Overlay.Host.Server/Components/Pages/TradePage.razor
Labels: ui/ux, deploy-env

#350 fix: add missing titles to desktop pages
  src/Arkanis.Overlay.Host.Desktop/UI/PageUrls.cs
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/InventoryPage.razor
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/SearchPage.razor
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/TradePage.razor
Labels: deploy-env, analytics
