Repository ArkanisCorporation/ArkanisOverlay, pull requests merged in 2025-08, with the labels that each got.

#356 fix: remove forgotten and unnecessary rendermode
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/TradePage.razor
Labels: ui/ux, deploy-env, critical

#359 fix: background data handling improvements
  src/Arkanis.Overlay.Components/Helpers/JsComponentInterop.cs
  src/Arkanis.Overlay.Domain/Models/Game/GameEntitySyncData.cs
  src/Arkanis.Overlay.Domain/Models/InternalDataState.cs
  src/Arkanis.Overlay.Domain/Models/SyncDataCache.cs
  src/Arkanis.Overlay.External.UEX/UexApiOptions.cs
  src/Arkanis.Overlay.Infrastructure/Data/Mappers/UexApiDtoMapper.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Local/UexGameEntityInMemoryRepository.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexGameEntitySyncRepositoryBase.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexItemPriceSyncRepository.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexItemTraitSyncRepository.cs
  src/Arkanis.Overlay.Infrastructure/Services/ExternalSyncDatabaseCacheProvider.cs
  src/Arkanis.Overlay.Infrastructure/Services/GameEntityRepositorySyncManager.cs
Labels: ui/ux, perf

#362 Release: RC
  .run/Arkanis.Overlay.Host.Desktop.run.xml
  .run/Arkanis.Overlay.Host.Server.run.xml
  .run/Seq Log Viewer.run.xml
  DEVELOPMENT.md
  Directory.Packages.props
  src/Arkanis.Overlay.Common/Arkanis.Overlay.Common.csproj
  src/Arkanis.Overlay.Common/Extensions/DependencyInjection.cs
  src/Arkanis.Overlay.Common/packages.lock.json
  src/Arkanis.Overlay.Components/Helpers/JsComponentInterop.cs
  src/Arkanis.Overlay.Components/packages.lock.json
  src/Arkanis.Overlay.Domain/Models/Game/GameEntitySyncData.cs
  src/Arkanis.Overlay.Domain/Models/InternalDataState.cs
  src/Arkanis.Overlay.Domain/Models/SyncDataCache.cs
  src/Arkanis.Overlay.Domain/packages.lock.json
  src/Arkanis.Overlay.External.UEX/UexApiOptions.cs
  src/Arkanis.Overlay.External.UEX/packages.lock.json
  src/Arkanis.Overlay.Host.Desktop/Arkanis.Overlay.Host.Desktop.csproj
  src/Arkanis.Overlay.Host.Desktop/Program.cs
  src/Arkanis.Overlay.Host.Desktop/UI/Pages/TradePage.razor
  src/Arkanis.Overlay.Host.Desktop/packages.lock.json
  src/Arkanis.Overlay.Host.Server/Arkanis.Overlay.Host.Server.csproj
  src/Arkanis.Overlay.Host.Server/DependencyInjection.cs
  src/Arkanis.Overlay.Host.Server/Program.cs
  src/Arkanis.Overlay.Host.Server/packages.lock.json
  src/Arkanis.Overlay.Infrastructure/Data/Mappers/UexApiDtoMapper.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Local/UexGameEntityInMemoryRepository.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexGameEntitySyncRepositoryBase.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexItemPriceSyncRepository.cs
  src/Arkanis.Overlay.Infrastructure/Repositories/Sync/UexItemTraitSyncRepository.cs
  src/Arkanis.Overlay.Infrastructure/Services/ExternalSyncDatabaseCacheProvider.cs
  src/Arkanis.Overlay.Infrastructure/Services/GameEntityRepositorySyncManager.cs
  src/Arkanis.Overlay.Infrastructure/packages.lock.json
  tests/Arkanis.Overlay.Common.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Host.Desktop.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Host.Server.UnitTests/packages.lock.json
  tests/Arkanis.Overlay.Infrastructure.UnitTests/packages.lock.json
Labels: release
